### ISSUE TITLE
Incompatible with Content Creator Integration

### ISSUE THREAD

**Issue by 2020Sanoj** [magicus/ModSettings#6]
This Mod is incompatible with https://www.curseforge.com/minecraft/mc-mods/content-creator-integration, it does not crash, but when I open the mod settings screen it takes a long time loading, and then it shows a blank page without the buttons from mods with a settings screen.

I don't use this mod, so for me, I don't need a fix for this, but I want to report it.

**Comment by magicus** [comment]
Content Creator Integration is hopelessly bad coded. :-( When asked to create a configuration screen, it runs a whole lot of code, which includes calling vanilla Screen.resize()! This will try to resize the Minecraft windows. If this was not bad enough, doing this will trigger Screen.init(), which will try to re-init all components on the current screen (which is in this case Mod Settings). The Mod Settings screen will try to, once again, create buttons for all plugins, querying the CCI mod in the process, which will once again resize the screen, and re-init. And so on until the stack overflows, causing the delay you see, and the blank page.

The reason this does not happen with Mod Menu is because CCI has a hard-coded special case for Mod Menu. *sigh*

This is really a bug with the CCI. I will see if there is any way I can work around it, though...

**Comment by magicus** [comment]
I managed to work around the crash, and can show a CCI button. However, having CCI loaded means your GUI scale will arbitrarly change when going into Mod Settings. This is due to a bug in CCI. I've opened a bug report on CCI, https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/issues/82.
